export const ACTION_GET_LANDING_PAGES = 'ACTION_GET_LANDING_PAGES'
export const ACTION_GET_LANDING_PAGE_BY_SLUG = 'ACTION_GET_LANDING_PAGE_BY_SLUG'
export const ACTION_DELETE_LANDING_PAGE = 'ACTION_DELETE_LANDING_PAGE'
export const ACTION_CREATE_LANDING_PAGE = 'ACTION_CREATE_LANDING_PAGE'

export const ACTION_UPDATE_PAGES = 'ACTION_UPDATE_PAGES'
export const ACTION_UPDATE_DRAFT = 'ACTION_UPDATE_DRAFT'

export const ACTION_DISMISS_ALERT = 'ACTION_DISMISS_ALERT'
export const ACTION_SHOW_ALERT = 'ACTION_SHOW_ALERT'

export const ACTION_GET_IMAGES = 'ACTION_GET_IMAGES'
export const ACTION_UPLOAD_IMAGE = 'ACTION_UPLOAD_IMAGE'
export const ACTION_FIND_IMAGE_BY_UUID = 'ACTION_FIND_IMAGE_BY_UUID'
export const ACTION_DELETE_IMAGE = 'ACTION_DELETE_IMAGE'
