export const MUTATION_SET_LANDING_PAGES = 'MUTATION_SET_LANDING_PAGES'
export const MUTATION_ADD_LANDING_PAGE = 'MUTATION_ADD_LANDING_PAGE'
export const MUTATION_DELETE_LANDING_PAGE = 'MUTATION_DELETE_LANDING_PAGE'
export const MUTATION_UPDATE_LANDING_PAGE = 'MUTATION_UPDATE_LANDING_PAGE'

export const MUTATION_SET_ALERT = 'MUTATION_SET_ALERT'

export const MUTATION_SET_IMAGES = 'MUTATION_SET_IMAGES'
export const MUTATION_ADD_IMAGE = 'MUTATION_ADD_IMAGE'
export const MUTATION_DELETE_IMAGE = 'MUTATION_DELETE_IMAGE'
