export const MUTATION_SET_LANDING_PAGES = 'MUTATION_SET_LANDING_PAGES'
export const MUTATION_ADD_LANDING_PAGE = 'MUTATION_ADD_LANDING_PAGE'
export const MUTATION_DELETE_LANDING_PAGE = 'MUTATION_DELETE_LANDING_PAGE'
export const MUTATION_UPDATE_LANDING_PAGE = 'MUTATION_UPDATE_LANDING_PAGE'

export const MUTATION_SET_ALERT = 'MUTATION_SET_ALERT'
